apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  initContainers:
  - name: install-plugin
    image: busybox
    command: ["sh", "-c", "echo 'Installing plugin...' && sleep 10"]
  containers:
  - name: main-app
    image: nginx
